title: Enviro Dashboard
description: Environmental Dashboard
url: "https://wizard-of-things.com/"
markdown: kramdown
permalink: /:title
google_analytics: 
youtube: https://www.youtube.com/user/sweska/videos
github:
  repository_url: https://github.com/wizard-of-things/envirodashboard
  raw_content_url: https://raw.githubusercontent.com/wizard-of-things/envirodashboard/master
exclude: ["datasheets", "Gemfile", "Gemfile.lock", "contributing.md", "Makefile", "readme.md", "scripts", "firmware"]
include: ["_data"]
