esphome:
  name: display_nextion
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: "IOTSlave"
  password: "TechnoMonk9#"

  manual_ip:
    static_ip: 192.168.1.108
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.1

  ap:
    ssid: "Esp NextionDisplay FB"
    password: "TechnoMonk99"

captive_portal:

web_server:
  port: 80

logger:


mqtt:
  broker: 192.168.1.165
  username: devmonk
  password: DevMonk99
  client_id: displaynextion@#$
  topic_prefix: display/nextion
  discovery: false
  reboot_timeout: 30s

ota:

time:
  - platform: sntp
    id: sntp_time


uart:
  rx_pin: D6
  tx_pin: D5
  baud_rate: 9600


text_sensor:
  - platform: mqtt_subscribe
    name: "bme280_temperature"
    id: bme280_temperature
    topic: update/nextion/temperature

  - platform: mqtt_subscribe
    name: "bme280_humidity"
    id: bme280_humidity
    topic: update/nextion/humidity

  - platform: mqtt_subscribe
    name: "bme280_pressure"
    id: bme280_pressure
    topic: update/nextion/pressure



display:
  - platform: nextion
    update_interval: 1s
    lambda: |-
      auto time = id(sntp_time).now();
      it.set_nextion_rtc_time(time);
      it.set_backlight_brightness(50);
      it.set_component_value("n0",time.hour);
      it.set_component_value("n1",time.minute);
      it.set_component_value("n2",time.second);
      it.set_component_text("t0",id(bme280_temperature).state.c_str());
      it.set_component_text("t1",id(bme280_humidity).state.c_str());
      it.set_component_text("t2",id(bme280_pressure).state.c_str());


